### ISSUE TITLE
BlightBoundFileDumper

### ISSUE THREAD

**Issue by Aegide** [Nodja/AwesomenautsFileDumper#1]
Hello,

_I recently found out that Blightbound also uses .binded files, and that your tool was the best (and the only) way available to read them._

_I was planning to use directly your tool, or to fork it, but then i realized i was missing something._

_I do not have a valid SBOX or a valid RCON for Blightbound's files, so when i try to decrypt data it remains obfuscated or it gives me an "list index out of range" error._

Could you please tell me how you found these values, or to show me ressources that could help me do the same ?

I'm beginning with crypto and it looks like an interesting project to me.

I know you haven't touched in a long time this project, but i would appreciate any kind of help!

**Comment by Nodja** [comment]
In the case of awesomenauts the SBOX and RCON were standard AES tables and not changed. What was changed was how the key expansion was done, it used a sha-1 of the utf-16 value of the relative path of the file and the file size to derive the key and IV, then used some weird key expansion algorithm based on the original AES one to expand those into round keys.

I can't recall the exact details. But you can probably figure it out by finding the AESENC instruction and go back from there.

Also it might be the case that it's just using different compression. My dumper assumes all files are either compressed with zlib or uncompressed. It doesn't know or try to guess, it just assumes anything not in the nodecrypt setting will be zlib compressed.

**Comment by Nodja** [comment]
Removing out any logic and force decrypting the files wields garbled data, so I assume they changed the algorithm. You're gonna have to reverse engineer the game and figure out what they changed.

**Comment by Aegide** [comment]
Thanks for the informations !
